### ISSUE TITLE
Should we check if dependencies are met?

### ISSUE THREAD

**Issue by FFY00** [FFY00/python-install#2]
I am not sure about this. This would be a feature for end users wanting to install wheels this way, but if you care about dependencies you might want to use a package manager like pip.

If we do check for dependencies, there will be a CLI option to turn it off/on (the opposite of whatever the default is). Like we have in https://github.com/FFY00/python-build.

**Comment by FFY00** [comment]
@pganssle, sorry to ping you. Do you have any opinion on this?

**Comment by pganssle** [comment]
I'm not sure I have enough context on this project to give good guidance, but if the idea here is that this will simply take a wheel and install it, it should at *most* be optional to check the dependency installation. One reason for this is that `pip` has no problem with cyclic dependencies because it's installing "X + X's dependency graph", so it doesn't matter if the dependency graph has cycles as long as they install every item in it. If `pip` doesn't have a problem with it, then people will end up doing it (not really the same as `install_requires` dependency cycles, but I recently was packaging `importlib_metadata` and `importlib_resources` for work and found that the tests of each one has a dependency on the other one). If you're just installing one wheel at a time, there will be situations where you cannot ensure that all dependencies are satisfied after each installation, only that the dependency graph is fully installed *after* all wheels have been installed.

Each package is installed along with its `METADATA`, though (as far as I know, I'm not an expert on this), so I'd be inclined to make a separate "verify dependency graph" function that can be done after the final installation step (it could still presumably be in this package if you want).

**Comment by FFY00** [comment]
> it should at _most_ be optional to check the dependency installation

I agree, this should be optional. One of the reasons is to be able to install wheel with cycle dependencies, as you pointed out. I don't really want to make this able to install multiple wheels at the same time, I don't think that really fits the intent of the project (but also would fall too far). Another reason is that I would pull https://github.com/pypa/packaging for this, which is an extra bootstrapping dependency.

For my specific use-case, I don't need this. I will be building the wheels and will verify the dependencies there (at least for PEP517). But I think using this to install wheels downloaded from the internet is a very valid use case.

> Each package is installed along with its `METADATA`, though (as far as I know, I'm not an expert on this), so I'd be inclined to make a separate "verify dependency graph" function that can be done after the final installation step (it could still presumably be in this package if you want).

Well, I would want it to run before the installation so that we can catch any issues before tainting the filesystem, especially since we do not provide an uninstaller.

**Comment by FFY00** [comment]
Okay, I added `--verify-dependencies` which will verify the dependencies.
